# Generated by Django 5.0 on 2023-12-26 17:20

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=django_resized.forms.ResizedImageField(crop=None, default='avatars/default/default.png', force_format='PNG', keep_meta=False, quality=-1, scale=None, size=[150, 150], upload_to='avatars/<function User.__int__ at 0x7f1c866818a0>/'),
        ),
    ]
